// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArmVDl-er1vNDyxYmb7exAtzvhaN4dRbI',
    appId: '1:899451152449:web:49cb905d9a52f16099bec0',
    messagingSenderId: '899451152449',
    projectId: 'fluttergram-73286',
    authDomain: 'fluttergram-73286.firebaseapp.com',
    storageBucket: 'fluttergram-73286.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWvJCrK5kZLfZaD5sghPwqcgLMCWTY9jM',
    appId: '1:899451152449:android:c52fe177ee89b0b999bec0',
    messagingSenderId: '899451152449',
    projectId: 'fluttergram-73286',
    storageBucket: 'fluttergram-73286.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzda0arLxauf3hqesaSW-zhjCsZLYkgHo',
    appId: '1:899451152449:ios:1b63484cf3a6fe8f99bec0',
    messagingSenderId: '899451152449',
    projectId: 'fluttergram-73286',
    storageBucket: 'fluttergram-73286.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
